version: "3.8"

services:
  server:
    image: kishorevbhosale/imagestore
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    #platform: linux/x86_64 in case of mac or linux
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: imagestore
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234